---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 47a5c1f6e910a0a82a5f2164c5f667d8aca0df2a
    app.quarkus.io/build-timestamp: 2023-03-17 - 11:11:36 +0000
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: app-market
  name: app-market
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: app-market
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 47a5c1f6e910a0a82a5f2164c5f667d8aca0df2a
        app.quarkus.io/build-timestamp: 2023-03-17 - 11:11:36 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: app-market
    spec:
      containers:
        - env:
            - name: dev
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: damosoft.internal.com:1100/damosoft/app-market:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8085
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: app-market
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
            - containerPort: 8085
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8085
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 47a5c1f6e910a0a82a5f2164c5f667d8aca0df2a
    app.quarkus.io/build-timestamp: 2023-03-17 - 11:11:36 +0000
  labels:
    app.kubernetes.io/name: app-market
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: app-market
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8085
  clusterIP: 0.0.0.0
  selector:
    app.kubernetes.io/name: app-market
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
